spring:
  jpa:
    detabase-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true
    properties:
      hibernate.format_sql: true
  jackson:
    time-zone: Asia/Seoul

  profiles:
    include: db, s3, email, jwt, oauth

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

server:
  tomcat:
    max-http-form-post-size: 50GB

