spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    group:
      dev: "dev, db-dev, s3-dev"
      prod: "prod, db-prod, s3-prod"
    include: email, jwt, oauth

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

server:
  tomcat:
    max-http-form-post-size: 50GB